# Generated by Django 4.0.5 on 2022-06-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_dean',
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField()),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dashboard.faculty')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.teacher')),
            ],
        ),
    ]
