# Generated by Django 4.0.5 on 2022-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_sessional',
            field=models.BooleanField(default=False),
        ),
    ]
