# Generated by Django 4.0.5 on 2022-06-21 12:00

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_remove_teacher_is_dean_dean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(max_length=11, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=account.models.get_profile_pictures_directory)),
                ('facutly', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.faculty')),
            ],
        ),
    ]
