# Generated by Django 4.0.5 on 2022-06-21 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_department_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_remove_teacher_id_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
