# Generated by Django 4.0.5 on 2022-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_routine_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='session',
            field=models.IntegerField(null=True),
        ),
    ]
