# Generated by Django 4.0.5 on 2022-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmember',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testmember',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
