# Generated by Django 4.0.5 on 2022-06-15 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_testmember_is_dean_testmember_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credits', models.FloatField()),
                ('code', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('semester', models.CharField(choices=[('I', 'I'), ('II', 'II')], default='I', max_length=2)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_test.testdepartment')),
            ],
        ),
    ]
